### ISSUE TITLE
ipa file?

### ISSUE THREAD

**Issue by OliverTheGamer** [clragon/e1547#10]
Hi!! im actually really new to GitHub and coding, but im having difficulty trying to download this app. i have a jailbroken iphone and have installed AppSync Unified, but i cant seem to find the ipa file anywhere.. any solution? thank you!!

**Comment by clragon** [comment]
Hi,

IPA releases are compiled by @CamperGuy and since I have just released 1.5,
you will sadly have to wait a little bit until I have time to ask him to compile this one.

This should only take a couple days however.

Regards!

**Comment by CamperGuy** [comment]
Hi, I will get around to it tomorrow morning as I've had a busy week.
@clragon I saw your response for issue #7 which I'll also take a look at. Prioritising the 1.5 ipa though

**Comment by CamperGuy** [comment]
Expect a 1.5.1 ipa file within a few hours @OliverTheGamer

**Comment by OliverTheGamer** [comment]
> Expect a 1.5.1 ipa file within a few hours @OliverTheGamer

thank you so much!! and also thank you so much @clragon for all the hard work <33 appreciate your time and effort put into this

**Comment by clragon** [comment]
@OliverTheGamer The IPA file is now added to the latest release.
Regards!
