### ISSUE TITLE
[ Bug ] No NSFW?

### ISSUE THREAD

**Issue by ALewdDev** [clragon/e1547#100]
Maybe I'm just a fucking idiot UwU but I can't 
seem to get the app to show explicit posts ..

- I'm logged in
- No filters / explicit filter
- Empty blacklist
- No safe mode on e6

**Comment by clragon** [comment]
The app defaults to `e926.net` as a host.
You can switch the host in the app settings.

**Comment by clragon** [comment]
- the app cannot offer a toggle for e621.net because its nsfw and the google play store does not allow that
- the Home page already saves your search
- There is a History of all posts and searches you have opened that you can check out

**Comment by ALewdDev** [comment]
@clragon Oh wow, that's stupid ( Google )

- Did you plan on publishing the app to the F-droid store as well?
- I know the home page saves the search query, however if you 
close -> reopen the app, the search will start from scratch
again, I'm wondering about a feature that for allows you to
continue where you left off 

( If I scrolled down like 1000 posts and enabled the 
feature, it would save the position of the search )

( Could be done with the post id if I'm not mistaken, since in the
query you can specify after what point to request posts from )

**Comment by clragon** [comment]
- #64
- no, this could not be done, because if you use a cursor to browse posts, your query parameters are now ignored
- You should join the discord instead of continously replying to this issue :3
