### ISSUE TITLE
Android downloads again

### ISSUE THREAD

**Issue by Kinectika** [clragon/e1547#106]
**Describe the bug**
Downloads either take about 3 minutes with the app froze or will repeatedly show the app not responding message even if the app comes back
**To Reproduce**
Set custom download directory and download a image

**Expected behavior**
Image downloads without freezing to custom directory

**Screenshots**

**Platform**

 - Device: Google Pixel 7 pro
 - OS: Android 13
 - Version 16.2.4

**Logs**

**Additional context**

**Comment by clragon** [comment]
Thank you for your report.
I have investigated and found the cause for this issue.

https://github.com/alexrintt/shared-storage/issues/144

I have implemented a workaround while we wait for upstream fixes.
It will ship with the next release.
