### ISSUE TITLE
Altstore Source File not being recognized

### ISSUE THREAD

**Issue by kannthus** [clragon/e1547#108]
**Describe the bug**

The JSON for the altstore source appears to not be working? 

**To Reproduce**

1. In Altstore Sources
2. Enter https://e1547.clynamic.net/assets/altstore.json
3. Errors out

**Expected behavior**
It adds E1547 as a source in Altstore

**Screenshots**

![IMG_4147](https://github.com/clragon/e1547/assets/32248891/08000f8a-7eee-477e-8cf6-53cb6db640c5)

**Platform**

 - Device: iPhone 14 Pro Max
 - OS: iOS 17
 - Version: N/A

**Logs**

**Additional context**

I've tried a bunch of variations of the URL, just in case it was me being silly.

**Comment by clragon** [comment]
Thank you for your report, I will take a look later.

**Comment by clragon** [comment]
I have updated the script that writes the json so now it should be valid again.

**Comment by kannthus** [comment]
Hey @clragon, That worked in adding the source file!

But unfortunately there appears to be another issue with it, errors out when I try to install from the source.
![image](https://github.com/clragon/e1547/assets/32248891/ea59f12c-bf37-4c30-8481-678a12914354)


Instead of making a new issue report, I'll bump this one, hope that's not an issue ❤️
