### ISSUE TITLE
Altstore Bundle ID doesn't match Source

### ISSUE THREAD

**Issue by kannthus** [clragon/e1547#109]
**Describe the bug**

Altstore appears unhappy that the bundle ID's aren't the same. Making it so the installation does not go through.

**To Reproduce**

1. When adding the Altstore Source
2. Attempt to install the APp
3. Errors out

**Expected behavior**

For the app to install.

**Screenshots**

![image](https://github.com/clragon/e1547/assets/32248891/2d769422-bb2e-419f-8337-f8d98a025980)

**Platform**

 - Device: iPhone 14 PM
 - OS: iOS 17
 - Version N/A

**Logs**
E1547 Could not be installed. The bundle ID "net.clynamic.e1547" does not match the one specified by the source ("net.e1547")

**Additional context**
Follow up of #108

**Comment by clragon** [comment]
thank you for your report.
I have updated the file again. Please let me know if it works this time!

**Comment by kannthus** [comment]
> thank you for your report. I have updated the file again. Please let me know if it works this time!

Tried it again, unfortunately a new error this time. Saying it's downloaded, however there is no instance of E1547 on my phone. Think I might just load the .ipa normally, might be easier haha. 
![](https://cdn.discordapp.com/attachments/766836236856983584/1149512344553148556/IMG_4272.png)

**Comment by clragon** [comment]
aw, bummer. I am sorry it doesnt work out. no idea how I could debug this... 
maybe that error means the version in the altstore file and the _app version_ of the file do not match?
its possible I have to strip the build number from there.

**Comment by clragon** [comment]
I have adjusted the version string so it matches the bundle version of the IPA.
I hope that fixes it.

**Comment by kannthus** [comment]
> I have adjusted the version string so it matches the bundle version of the IPA. I hope that fixes it.

Hey, that appears to have fixed it! It worked now 🎉
