### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [clragon/e1547#110]
https://gitlab.com/fdroid/fdroiddata/-/jobs/5101382825

Could you please take a look? Thanks!

**Comment by clragon** [comment]
Ah, I see. I also had this issue in my github runner. 
A library which we depend on suddenly demands java 17 minimum.

**Comment by clragon** [comment]
Ive released a new version that uses the exact flutter version as specified in my pubspec.yaml.
The PR over at gitlab includes that script so it should all match up.

**Comment by linsui** [comment]
Thanks!
