### ISSUE TITLE
Allow option for incognito keyboard

### ISSUE THREAD

**Issue by fwuffyboi** [clragon/e1547#112]
**Describe the solution you'd like**
Give users the option to "Set keyboard to incognito mode" when using the app. Since currently, using the app and typing in it allows the google keyboard (and very likely others) to save what the user has typed into memory, and this can be used for future personalised suggestions. and since this app can be used for pornography, these suggestions can be quite inappropriate at times. TIA.

**Comment by clragon** [comment]
I have planned out the solution for this, but implementation is tedious and I wish for a simpler solution provided by the framework. While we wait for that, this issue is blocked by upstream.

**Comment by clragon** [comment]
The issue we are waiting for can be found here:
https://github.com/flutter/flutter/issues/144093

**Comment by clragon** [comment]
this has now been implemented and will be available in the next release.
