### ISSUE TITLE
[Feature request] Backup and recovery of settings and preferences

### ISSUE THREAD

**Issue by Terkyz** [clragon/e1547#114]
**Is your feature request related to a problem? Please describe.**
Yes, I personally use e1547 without an account and I don't really see a way to backup my preferences like the tags I have in the blacklist or my subscriptions or my settings like requiring authentication when logging into the app.

**Describe the solution you'd like**.
A simple way to backup and recover the backup of those preferences and settings with a button in the app settings.

**Describe alternatives you've considered**
I guess I can login with an e621 account but I have no need to do so. I also looked to see if this feature was already implemented but I didn't find anything about it.

**Additional context**
Thanks.

**Comment by clragon** [comment]
Thank you for your issue. 
I have considered how to implement this but have not reached a conclusive plan yet.
I will close this issue in favour of #83.
