### ISSUE TITLE
Failed to install an iPad Air 5th gen with AltStore

### ISSUE THREAD

**Issue by Dividedby0KSJ** [clragon/e1547#117]
**Describe the bug**
when trying to install with AltStore, it produces this bug report see attached.

**To Reproduce**
install app using AltStore on iPad Air fifth gen running iPadOS 17+

**Expected behavior**
for the app to be installed

**Screenshots**

![IMG_0026](https://github.com/clragon/e1547/assets/44017376/5e82533d-730c-4533-a07f-5818fe752bdd)

**Platform**

 - Device: iPad Air 5th gen
 - OS: 17.2
 - Version 17.0.0 [https://github.com/clragon/e1547/releases/](url)

**Logs**

/Users/rileytestut/Developer/Projects/AltStore/Dependencies/AltSign/AltSign/ldid/../../Dependencies/ldid/ldid.cpp(1368): _assert(): end >= size - 0x10

**Additional context**
I also noticed that the main readme.MD does not mention old store anymore. Instead, mentions something different is old store not supported anymore?

**Comment by clragon** [comment]
AltStore is currently experiencing some technical issues. 
As an alternative, we recommend using Sideloadly (https://sideloadly.io/). 

Moreover, we have received multiple reports indicating that version 17.0.0 crashes when the search feature is accessed on iOS 17 and above. To avoid this issue, we suggest using version 16.3 or the 18 beta (accessible through the discord).
