### ISSUE TITLE
ipa file? the sequel

### ISSUE THREAD

**Issue by CinderFox101** [clragon/e1547#12]
this isn’t really a bug or issue but i may have some more ideas to help you out, you can email me if you want but i just wanna help is all... helping makes me feel important lol

**Comment by clragon** [comment]
Did you perhaps mean IPA file?
Sorry, I often push new releases that are mostly fixes without notifying @CamperGuy 
I'll try to make sure IPA files are avalable more often.

**Comment by CinderFox101** [comment]
sorry, lol... anyway, is is possible to get the app to update from inapp, i understand if not but it would be cool, and also... good work... you’ve been doing amazing

**Comment by clragon** [comment]
Updating from inapp is impossible, especially so on iOS.
I could probably download and even launch the installer for the APK file on android,
but there is no chance of this happening for iOS.

I added an IPA file for the newest release.
