### ISSUE TITLE
App freezes when trying to search

### ISSUE THREAD

**Issue by Paradastra** [clragon/e1547#121]
App freezes when trying to search. The issue occurs in latest update of e1547 on iOS 16 public beta 3. App was loaded with sideloadly x32. It's not a crash, but if you try to tap anything, it won't work.
If needed more details - please let me know!

**Comment by clragon** [comment]
Hi,

Thank you for your report.
This is a known bug in version e1547 v17 on iOS. 
We hope to have this bug fixed next relase. You can get an early beta in our [discord](https://discord.clynamic.net).

Best regards.
