### ISSUE TITLE
"post info" setting was lost in settings page layout improvement?

### ISSUE THREAD

**Issue by ilyamikheevcoder** [clragon/e1547#122]
**Describe the bug**
There is no option to toggle display of info on post tiles. It was removed in the commit 25ae342, seemingly by error, as it is still present internally, and may even be set by editing the config file.

1. Go to Settings
2. Where "post info".

**Expected behavior**
I should be able to toggle the display of post info in the post tiles.

**Screenshots**
Opening the Settings page should suffice.

**Platform**

 - Device: Motorola Moto G36
 - OS: Android 13
 - Version: 18.0.0

**Logs**
In it's own way, the commit mentioned is also a log entry of this app's development.

**Additional context**
I personally mitigated this issue by breaking into the app's config file with my rooted permissions, and modifying this setting manually. Not everybody is so nerdy though!

**Comment by clragon** [comment]
oopsie woopsie!

**Comment by clragon** [comment]
I have restored the setting. It will be available again in the next release.
