### ISSUE TITLE
Pool/Artist name download folders

### ISSUE THREAD

**Issue by CanglanXYA** [clragon/e1547#123]
**Is your feature request related to a problem? Please describe.**

Its hard and time-consuming for user who want to download a bunch of images from different artists and arrange them in order manually

**Describe the solution you'd like**

All images downloaded are redirected to folders which names are renamed by artists or pool name

**Describe alternatives you've considered**

**Additional context**

**Comment by clragon** [comment]
This seems like good feature to have...
I just have to come up with a clear spec.

What if an image has multiple artists?
Or multiple pools?
Or both?

Which of these folder names will the app pick?

**Comment by clragon** [comment]
> Without Database method

This would duplicate the images accross many places which I am not sure if this is optimal.
However, implementing this would not be too difficult. 

> Database method

This is another feature, where Iimplement a new client that works with a local database to which posts (and all other objects) can be saved, essentially representing a local image server.

This feature is very complex and while I am moving towards making such a thing possible, the ETA is very far away.

**Comment by clragon** [comment]
Hi @CanglanXYA, 
I have opened a new issue #126. Please let me know if it would solve your problem accurately.
Thank you and best regards!
