### ISSUE TITLE
Pool name download folders

### ISSUE THREAD

**Issue by Terkyz** [clragon/e1547#124]
**Is your feature request related to a problem? Please describe.**
Not at all, but I think that it would be better if instead of mixing my others downloads with the images of my pool, it would be better if the pools have their own directory.

**Describe the solution you'd like**
Let's suppose I download a pool and my download directory is /Downloads, when downloading a pool named "Cats", instead of downloading everything directly to /Downloads, create a new directory with the pool name "Cats" and put the images of the pool there.

**Describe alternatives you've considered**
Organizing it by myself.

**Additional context**

**Comment by clragon** [comment]
Thank you for your request.
Your proposal is very similar to #123.
Are you only interested in Pool folder names or would you also like Artist folder names?
Best regards.

**Comment by Terkyz** [comment]
Oh, my bad, I didn't see that issue. My idea was only pools but artist folder also would be super useful. I'll close the issue since I believe it's duplicated.
