### ISSUE TITLE
Slideshow Option

### ISSUE THREAD

**Issue by Dvdboy42** [clragon/e1547#128]
**Is your feature request related to a problem? Please describe.**

Not related to a problem

**Describe the solution you'd like**

Adding a slideshow feature would be amazing, considering many such websites/apps have one. for any given search or set of results, there should be an option somewhere to start a slideshow of the current results. A configurable time per post or configurable transition would be nice, but not necessary 

**Describe alternatives you've considered**

**Additional context**

Could be located and enabled in a submenu in settings, or just hidden in a drop-down list in order to not clutter the visual experience

**Comment by clragon** [comment]
Thank you for your issue. I will consolidate it with #88
