### ISSUE TITLE
Immediately crashes when opening the app 

### ISSUE THREAD

**Issue by GalaxiumNation** [clragon/e1547#133]
(the title)

**To Reproduce**
open app.

**Expected behavior**
expected to open like normal

HTC Desire 510
Android 4.4.2 (non-root)

I was using the latest version from fdroid (the latest that works on android 4.4.2)
I've also tried a few older versions with the same result.

One that seems to work ok i think is 18.0.0

**Comment by clragon** [comment]
Marking this issue as stale. Please reopen it, if this is still relevant.
