### ISSUE TITLE
Flag in the corner of new posts from a tag

### ISSUE THREAD

**Issue by themostlogicalsolution** [clragon/e1547#138]
**Is your feature request related to a problem? Please describe.**

I like to see and download new posts from artists and tags. Whenever I see "n new posts" under a subscription, I end up counting until I reach the nth most recent post before swiping back up

**Describe the solution you'd like**

A flag in the corner of new posts (or some other special highlight)

**Describe alternatives you've considered**

Perhaps a toggle to only show new posts from a tag

**Additional context**

Here's what it could look like:
![Screenshot_20240811_103012](https://github.com/user-attachments/assets/0a56f7c9-8b36-4c79-89c1-88e6dfc7349d)
![Screenshot_20240811_103125](https://github.com/user-attachments/assets/51f2f4d8-ee40-4c99-a24a-636aad7269c9)

**Comment by clragon** [comment]
Unfortunately, the way the current update mechanism works, does not allow us to know exactly how many new posts there are with certainty. This limitation was added as a way of making sure we don't make too many API requests and get bogged down in loading new posts from just one artist. This is also why the counter for new posts stops at 5, only displaying "5+". 
I am open to suggestions.
