### ISSUE TITLE
Memory leak in newer iOS builds 

### ISSUE THREAD

**Issue by KritantaDev** [clragon/e1547#14]
App crashes about 10-15 seconds after opening due to a memory leak which quickly exceeds app limits. 

Will try to provide more info when possible

**Comment by clragon** [comment]
Could you tell me;
1. which version of the app this occurs on
2. which device you are using
3. what OS version you are on?

Also, are there any notable steps you are taking for this to occur?
Did this issue happen after an update?

**Comment by clragon** [comment]
@CamperGuy could you give this a good look?

**Comment by clragon** [comment]
I'm gonna close this, assuming it works again.
