### ISSUE TITLE
Video results begin to buffer endlessly after a few videos. 

### ISSUE THREAD

**Issue by Ragged-Hellion** [clragon/e1547#18]
Android 7, App v. 1.7.0.
When browsing video results, the first few videos buffer, play, and loop just fine. However, after those first few, later results cease to play entirely and play the bufferimg animation seemingly indefinitely -and internet speed is not the limitation.

**Comment by clragon** [comment]
Hi,

thanks for reporting this.
I have noticed this myself, it seems that some videos kind of crash the video player instance;

I havent found a way to restart it while the app is running which is quite weird. 
I will look into it when I can.

**Comment by clragon** [comment]
This is more or less an upstream issue, but I still think its possible to fixit from here.
For reference:
https://github.com/flutter/flutter/issues/61309

**Comment by clragon** [comment]
currently trying to fix this.
simply discarding the controllers doesnt seem to work well and causes issues in the gallery.
I will look into it again later.

**Comment by clragon** [comment]
This should be fixed.
I have included a new mechanic that will dispose of old controllers by keeping track
of all initialized controllers and disposing when new ones are made. 

if this issue still occurs in the next update, please reopen this issue.

**Comment by unoravi** [comment]
@clragon 
I have Video Dispose Memory issue : https://github.com/flutter/flutter/issues/79546 

Can you help me out on it ? Please let me know if any more details required.

Thanks

**Comment by clragon** [comment]
@unoravi 
your issue seems to be completely different from the issue that is mentioned here.
I can unfortunately not help you.
