### ISSUE TITLE
OS Error: Permission denied errno=13

### ISSUE THREAD

**Issue by UnknownDuck19** [clragon/e1547#2]
I am unable to download images using this app. I believe it is down to Android 10 and how it handles saving to SD Cards, but I may be very wrong.

**Comment by clragon** [comment]
Thank you for reporting this. 
I've already had this bug on my radar, but you motivated me to look into it again.

You were spot in by the way, it's an issue with a new permission system in android 10.
I haven't figured out how to use it, the documentation seems to be hidden in some unreachable place of the internet (I can't find it), so we're using the legacy option in the manifest to fix this. 

I'll release this as a hot patch now, so your downloads should work soon.
