### ISSUE TITLE
Following preview shows blacklisted posts

### ISSUE THREAD

**Issue by Kinectika** [clragon/e1547#33]
Following preview shows blacklisted posts as new and previews images until tapped on then it disappears when you go back.

Example:
![Screenshot_20211031-131134](https://user-images.githubusercontent.com/48077461/139596428-bdff7bde-c5d4-4c9c-8f29-53dad3e74ed7.jpg)
![Screenshot_20211031-131140](https://user-images.githubusercontent.com/48077461/139596432-30b525eb-8402-4778-947c-8a3dd8815527.jpg)
![Screenshot_20211031-131211](https://user-images.githubusercontent.com/48077461/139596433-e374804d-dbf0-4307-b371-7f121117b731.jpg)

**Comment by clragon** [comment]
Thank you for reporting this.
I have fixed the issue in 293f0a3.
It will be shipped with the next patch.
