### ISSUE TITLE
[Enhancement] Full focus on gallery view

### ISSUE THREAD

**Issue by KritantaDev** [clragon/e1547#4]
I do feel like the amount of screen-space the tags eat up now is a bit of a regression from version one, and I’d personally like to see an option to hide all of the tags and such and go fully-black except for the image

**Comment by clragon** [comment]
When tapping an image, the app will go full screen with that image.
However, it is currently not possible to swipe through images this way.

This is already planned, but there is one issue;
The way images are loaded with endless pages is locally handled and needs to be overhauled, so it can be passed on to the image page and the fullscreen page. 
This would then allow it to swipe forever. 

I've done multiple attempts to implement this by now but no success.
Though I have some new things I can try.

In the meantime I might also be able to implement swiping through fullscreen posts, without endless loading though.

How does that sound?

If that's not what you're looking for, I might be able to implement a "minimal mode" which reduces the screen to just the image and the favorite button, perhaps? I dont know how hard this could turn out though. I was also thinking about having a bar at the bottom with an arrow up that opens tags etc in fullscreen. 

You will have to wait a while for these changes though, my finals are comming up in around 2 weeks, and I cannot dedicate any time to development right now, sadly.

Regards

**Comment by KritantaDev** [comment]
I do intend to take a shot at this myself as well, although given a lack of dart experience that may not end well; best of luck on your finals :)

**Comment by clragon** [comment]
I implemented swiping through fullscreen images.

Loading new images while doing so, or while swiping through the normal image view is not yet implemented, but still planned and likely compatible with this implementation of swiping.
