### ISSUE TITLE
User data parsing fails

### ISSUE THREAD

**Issue by erisdev** [clragon/e1547#63]
i couldn't figure out how to reply on the play store...

![Screenshot_20220214-015459_e1547](https://user-images.githubusercontent.com/143007/153892201-576ca966-28a1-4a12-92cd-2c0156c57960.png)

so, i get this error any time i try to modify my blacklist, and the list itself shows up blank, as you can see. my blacklist is fairly simple—less than 20 items and only single tags.

i'm logged in and able to view and edit favorites and such with no issue, but of potential interest, if i click my username in the settings, i get "Failed to load user". i haven't encountered any other issues accessing my account through the app so far, and i can view other user profiles just fine too. the only thing i can think of is maybe having a dot in my username is fucking something up?

**Comment by clragon** [comment]
Hi, its possible that the parser for user data somehow fails to process your user correctly.
The dot shouldnt be an issue though.

Could you tell us what your username is? If you cannot visit your own user profile page,
that hints that there is some discrepancy between the public user data and the parser.

**Comment by clragon** [comment]
Also from your screenshot we can see that the bottom bar has fallen behind your navigation bar. interesting!
We assume thats because of edge to edge mode on android.
We will try to employ a fix for the next version.

**Comment by erisdev** [comment]
apologies for the delay, i'm currently out of town for anthro new england and haven't been online much.

i'd rather not have my username publicly associated with my github account, but could i send it to you privately somehow?

**Comment by clragon** [comment]
sure thing, we have a [discord server](https://discord.gg/MRwKGqfmUz) for the app where you can find me,
or we also have a support email on the playstore.

**Comment by erisdev** [comment]
oh, hell, i forgot to respond to this—my apologies! i was out of town and just got back mid last week.

i am not sure that commit is going to fix the issue. i had a look at the api response for my user account and none of the fields appear tobe missing, including the one that was removed. i'll hop on the discord momentarily!

**Comment by erisdev** [comment]
for the curious: the problem was most likely related to my username having a dot in it. the api endpoint was throwing a 404 and changing my username to one without a dot fixed it. no relation to the new bug the commit above fixed!
