### ISSUE TITLE
Release on FDroid

### ISSUE THREAD

**Issue by Vulldozer** [clragon/e1547#64]
I tired the app for a while and it's great
It would be cool if it was released on the FDroid store

**Comment by clragon** [comment]
Hi,
If you would like to see e1547 on fdroid, you can submit a request to the fdroid repository or write a metadata file and make a merge request there.

The instructions can be found on their site: https://f-droid.org/en/docs/Inclusion_How-To/
The submission does not require you to be a developer of the app.

Once submitted, the updates there should be automatic.
If you happen to submit the app there, let me know and I could add a download link on https://e1547.clynamic.net.

**Comment by Vulldozer** [comment]
I've opened an issue instead of writing a metadata file so might take days or weeks for a response. https://gitlab.com/fdroid/rfp/-/issues/2153

**Comment by Vulldozer** [comment]
From the issue submitted to F-Droid:
_____________________________
Fastlane

Error!
Fastlane was not found in your repo!
Without Fastlane, it is not possible to have app screenshots and the app description cannot be updated without going through the F-Droid team, causing unnecessary delays.
It is very strongly recommended to establish Fastlane in your repo.
_____________________________

I don't think this will prevent the app from being released on the F-Droid store but adding it could be beneficial.

**Comment by clragon** [comment]
I have attempted to set up fastlane 
and was immediately stopped by having to install ruby to do so and it failing to comply with me.
I might try again some time.

**Comment by clragon** [comment]
I have added fastlane to the repository.
I will look into automatically generating screenshots with it.

**Comment by clragon** [comment]
I have now opened a merge request with a config file for e1547.

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13540

**Comment by clragon** [comment]
The build config for e1547 has been merged and the app should be available on fdroid at some point in the near future.
