### ISSUE TITLE
Deleted children posts are shown

### ISSUE THREAD

**Issue by NameNotFinal** [clragon/e1547#65]
**Bug:** Whenever a post had a deleted child (usually from a reupload) it still shows up under the "Children" tab.

Example:
![image](https://user-images.githubusercontent.com/50883546/156850425-03ecc4e1-c09d-4e55-8b70-49374389918d.png)
Both of the children are deleted on this post, yet they still show.

Hopefully this should be an easy fix

**Comment by clragon** [comment]
Hi there,

sadly we cannot fix this issue, as the e6 API always returns all posts as children,
and we do not receive any information on whether they are deleted or not.

To figure out whether they are, we would need to request them specifically, which would mean one extra API request per child/parent post, which is way too much.

The site itself bypasses this problem by having direct database access when generating the HTML and not using the API at all.

This is the reason for many problems of reproducability of the sites functionality.

**Comment by NameNotFinal** [comment]
Oh, I understand the decision to not spam their API.

However, would it be possible to check if "has_active_children" is false in the case, where there are only deleted children posts (like it is in my example)? It doesn't require any extra API calls, and while it of course doesn't fix the problem in all cases it should still fix a majority of single images that have been reuploaded.

**Comment by clragon** [comment]
That is a lovely idea, I will implement that for the next release.
Thank you for bringing this to my attention!
