### ISSUE TITLE
Blacklist keyword alt method for gating NSFW posts

### ISSUE THREAD

**Issue by perlatus** [clragon/e1547#71]
Rather than making the domain name the primary way of controlling access to NSFW content, I think it would be better to have a keyword that needs to be added to a user's blacklist, such as `e1547_enable_explicit_I_am_18_or_older`. This keyword would need to be filtered out by the in-app blacklist configuration, so that it can't be added from the app.

If anonymous, or logged in but without the keyword, then explicit posts would be filtered client-side regardless of the domain.

I believe this would satisfy even Apple's requirements, since it requires a user to make an account and explicitly enable it on the website (like reddit frontends).

**Comment by clragon** [comment]
if we want to verify that users have an account before allowing them to access NSFW content, 
we can simply hide the server host toggle until the server has logged in.
