### ISSUE TITLE
All posts fail to download

### ISSUE THREAD

**Issue by IC-Dyllac** [clragon/e1547#72]
No matter what post I try to download all of them show the message "Failed to download post #(post number)"

e1547 version: 10.1.3
Android version: 10

**Comment by clragon** [comment]
Hi there,

have you made sure that the app was granted access to the device storage?

you can check the app permissions in the phone settings.

**Comment by clragon** [comment]
Hi there,

I have attached a modified version which allows you to access the app's exception logs in the settings.
Could you install it and extract the error for us?

When you are done you can go back to the normal version by triggering an update in the playstore or installing the normal APK download again.
You do not have to uninstall the app to install this update or to go back to the normal version.

[app-release.zip](https://github.com/clragon/e1547/files/8764397/app-release.zip)

**Comment by IC-Dyllac** [comment]
Hey, sorry for the delay. Here is what the log says:
exception occorued: FileSystemException: Creation failed, path = '/sdcard/Pictures/e1547' (OS Error: Permission denied, errno = 13)
with trace: #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      Downloading.download (package:e1547/post/data/actions.dart:145)
<asynchronous suspension>
#3      loadingNotification (package:e1547/interface/widgets/snackbar.dart:78)
<asynchronous suspension>

As a side note, I'm seeing that it's trying to write to the SD card. And I do remember that the other apps that wanted to write to the sd card opened a window where I had to give access to the SD card specifically. I attatch a picture of this specific window
![Access](https://user-images.githubusercontent.com/56610544/170846010-4ff3bd01-03c0-48f4-aa43-05fd8b142105.png)

**Comment by IC-Dyllac** [comment]
Indeed the problem persists.

EXCEPTION | 1:47:23 PM.654


FileSystemException: Cannot copy file to '/storage/emulated/0/Pictures/e1547/f-r95 - 3425822.png', path = '/data/user/0/net.e1547/cache/libCachedImageData/93701250-fb00-11ec-92a9-99d3c70cbf5b.png' (OS Error: Permission denied, errno = 13)

#0      _File.copy.<anonymous closure> (dart:io/file_impl.dart:328)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      ForwardingFile.copy (package:file/src/forwarding/forwarding_file.dart:26)
<asynchronous suspension>
#3      Downloading.download (package:e1547/post/data/actions.dart:146)
<asynchronous suspension>

**Comment by IC-Dyllac** [comment]
I'm not good at programming but I tried doing my own build (debug version, since release failed for reasons) using the fix I read here on [stackoverflow](https://stackoverflow.com/questions/60558577/how-to-solve-os-error-permission-denied-errno-13-in-flutter) by adding the "requestLegacyExternalStorage", and the file was able to save without issue. I have no idea if it was because of that or because I built a debug version that it didn't fail at saving the file. I think it's worth mentioning it.

In any case, thank you for your hard work.

**Comment by clragon** [comment]
unfortunately we cannot employ that fix because as the name implies, 
that option is a piece of legacy code and the google play store will not allow releasing the app with such an option enabled,
and it will be ignored on newer android versions.

this issue seems to be related to the Storage Access Framework that google has introduced.
I will look into fixing this but what they have created is a huge pain in the ass for all developers (which couldve been solved nicer with no loss of benefits).

**Comment by clragon** [comment]
this should now finally be fixed. let us know if it is not.

**Comment by IC-Dyllac** [comment]
I can confirm the issue was fixed
