### ISSUE TITLE
Can not turn off Biometric Auth [iOS]

### ISSUE THREAD

**Issue by Lil-Dragon** [clragon/e1547#73]
On iOS 14.8, with a jailbroken iPhone 8, if you turn on this feature by accident, you will not be able to turn it off cause the device will restart if you set a passcode. You can not change this setting once you turned it on either, so you are locked out of the app permanently.

**Comment by clragon** [comment]
Hi there,
we sadly cant figure out what your issue is.

Could you elaborate on how exactly you have locked yourself out of the app?

**Comment by Lil-Dragon** [comment]
Alright, so when I went into settings, I tapped the bio auth option. When you do that, it will not let you turn it off unless you have a passcode on your device. In my case, if I turn on a passcode, the jailbreak will panic and the device restarts, so I will lose access to both the app and my jailbreak. I have tried to delete and reinstall  the app, but that does not work. Does that make any sense?

**Comment by clragon** [comment]
you have to allow e1547 to use face ID for biometric auth to function correctly. 
you can do so in the system settings.
if you do not want to do that, please set a pin code so you can disable the lock.
if you do not want to do that either, please wipe the app data, which will reset the lock (this means all local data like follows and history are deleted).

**Comment by clragon** [comment]
I am sorry, that does not make any sense, no.
apps on iOS do not keep data over uninstallation.
I dont think I can do much for you to fix this issue, as it seems to be some reaction of your jailbroken iPhone, so I will close this.
Let me know if you would need help regardless.
