### ISSUE TITLE
Restore combined follows

### ISSUE THREAD

**Issue by Vulldozer** [clragon/e1547#74]
An option to see all posts by all the artists you follow simultaneously would be appreciated.

**Comment by clragon** [comment]
hi there,
do you mean a behaviour similar to the "combined" follow screen in version 10.x.x?

**Comment by Vulldozer** [comment]
Yes, I no longer have that option.

**Comment by clragon** [comment]
we have removed that feature because we think of it as inferior to the "split" follow screen.
it might return differently as there are some plans for upgrading the follow mechanic.

**Comment by Vulldozer** [comment]
Maybe it can be a toggle in the follow options menu

**Comment by clragon** [comment]
you mean how iut has been in version 10.x.x?

**Comment by Vulldozer** [comment]
> you mean how it has been in version 10.x.x?

Yes exactly like that, it doesn't have to replace the new split following page, it can be a toggle in the settings menu/following sidebar.

**Comment by clragon** [comment]
would this mean you want to just see the latest posts of those artists, or only posts you havent seen yet?

**Comment by Vulldozer** [comment]
The latest posts.

**Comment by Vulldozer** [comment]
I guess so,but both options can coexists but be switched using a toggle button

**Comment by clragon** [comment]
I think I will bring this feature back when I am migrating follows to the sql database in version 13.x.x

**Comment by clragon** [comment]
@Vulldozer in the current beta of the app, I have restored the combined follow screen but with a different UI.
The beta is available on the discord server or over this [direct apk link](https://cdn.discordapp.com/attachments/763322871598546954/1018358370564055120/app-release.apk).

I would be interested to hear if you would prefer this UI over the old one.
