### ISSUE TITLE
Blacklist is not loaded right after login

### ISSUE THREAD

**Issue by furrymetaphor** [clragon/e1547#78]
When logging in, the user's blacklist is not fetched until the app is refreshed.
It's not (just) a visual glitch. While in this state, posts that should be hidden continue to show, and any change to the blacklist overwrites the user's blacklist in the server.

Steps to reproduce:
- Open the app without being logged in
- Log in
- Go to Settings > Blacklist
  - Empty (or keeping old local tags)
- Restart the app
- Go to Settings > Blacklist
  - Tags have now been fetched from the server

e1547 12.0.0
Android 10

**Comment by clragon** [comment]
thank you for reporting this.
the denylist service doesnt seem to sync when the client authentication changes.
I will fix this for the next update!
