### ISSUE TITLE
Hide app in task manager

### ISSUE THREAD

**Issue by dankcatlord** [clragon/e1547#84]
When I open my app switcher, I would like the app to hide the preview so people can't see what I'm looking at when I have the app switcher open.

**Comment by clragon** [comment]
This feature will prevent taking screenshots of the app.

For reference: https://pub.dev/packages/secure_app_switcher

**Comment by dankcatlord** [comment]
In Firefox Focus, you can toggle on and off "stealth mode" in the settings. So you could have it turned off by default and people could still take screenshots.

**Comment by clragon** [comment]
yes, that is correct. this feature will obviously be disabled by default.

**Comment by clragon** [comment]
done in 2913504a5dbbe53d10b2d15ab4663d5726e81bf5, scheduled for the next release.
