### ISSUE TITLE
Cloudflare Support

### ISSUE THREAD

**Issue by dankcatlord** [clragon/e1547#87]
When the app connects to e621 when they ddos protection on, the app may get a 503 error with a cloudflare challenge page. When you get through this challenge page in a browser, a cookie gets set called `cf_clearance` as a session token and you are redirected back to the page you were trying to go to. I suggest that when one of these challenge pages is encountered, a browser window gets opened up to solve the challenge and the app would save the `cf_clearance` cookie for future requests.

**Comment by clragon** [comment]
implemented for next release
