### ISSUE TITLE
Unable to interact with last image/post

### ISSUE THREAD

**Issue by Webscratcher** [clragon/e1547#9]
Version used: 1.5.1 (Android)
Android 10 (on OP6)

I noticed that when I reach the last image/post in a search I'm unable to scroll or interact with this post in any way.

This includes all present buttons (navigation, menu, tags, etc).

The only way to get out is to either swipe to the previous post or use system navigation to exit.

**Comment by clragon** [comment]
Hi,

This is a known issue indeed, and it is probably related to the double post issue.
I can currently reproduce and test it reliably, but I haven't found the cause or a solution.

I will try to fix this when I have time.

**Comment by clragon** [comment]
this is an upstream issue, but I fixed it with a hack until they fix the pageviewer (if ever).
