### ISSUE TITLE
The app has stopped functioning, almost in it's entirety

### ISSUE THREAD

**Issue by Smol-Cynder** [clragon/e1547#92]
Username, and API key are correct, and network connection is stable, I'm also on the most recent version, yet the only function that seems operational is the history preview. Tapping on a post fails to load it.
![Screenshot_20230415-055743](https://user-images.githubusercontent.com/130836633/232209913-4d57ff08-f986-4d9e-adf1-aff2e6ee374a.jpg)
![Screenshot_20230415-055730](https://user-images.githubusercontent.com/130836633/232209916-a841d5cc-c109-45a3-906b-0c08872806ef.jpg)

**Comment by jojoto** [comment]
Same issue here (and #91 too).

I think the cloudflare protection is the possible cause...

I gonna check the logcat to see if the app returns any additional information for @clragon

**Comment by clragon** [comment]
the site is having issues and has therefore enabled DDOS protection, blocking the API usage.
This means the app can not reach the server for the duration. Please be patient while the site staff resolves this.
There is nothing we can do on our end.
