### ISSUE TITLE
Host cannot be reached (e621)

### ISSUE THREAD

**Issue by Dwegg0** [clragon/e1547#93]
This was working about a week ago before e6 went down for a "major software update" a couple days ago. I'm guessing a major change in their API too? I also included my own API key and still the problem persists, even though we all see e621 site being up as of making this issue. It used to work by just adding the domain without needing a full URL for it to work, without any issues ("e621.net"), now nothing works and it keeps reporting it to be unreachable. I've tried clearing app data, reinstalling from the Googles App store, even downloading latest release off this repo, have not tried to build it myself because I am just a bit too lazy. FYI, e926 works fine.

This is what I'm getting:
![Screenshot_20230415-145731](https://user-images.githubusercontent.com/76007630/232229063-440ceed6-ccdc-4bda-b03e-411d8506e0a0.png)

**Comment by clragon** [comment]
the site is having issues and has therefore enabled DDOS protection, blocking the API usage.
This means the app can not reach the server for the duration. Please be patient while the site staff resolves this.
There is nothing we can do on our end.
