### ISSUE TITLE
The request returned an invalid status code of 403.

### ISSUE THREAD

**Issue by ReDarkTechnology** [clragon/e1547#94]
So, I used Cloudflares 1.1.1.1 to access this but it somehow refused to do load pages, maybe something is broken?
My device is a Xiaomi M1 with Android 9

Here's the stack trace

EXCEPTION | 01:54:34.258

DioError [bad response]: The request returned an invalid status code of 403.

StackTrace: #0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:530)
#1      _RootZone.runBinary (dart:async/zone.dart:1665)
#2      _FutureListener.handleError (dart:async/future_impl.dart:162)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#4      Future._propagateToListeners (dart:async/future_impl.dart:800)
#5      Future._completeError (dart:async/future_impl.dart:575)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:51)
#7      _Completer.completeError (dart:async/future_impl.dart:23)
#8      Future.any.onError (dart:async/future.dart:617)
#9      _RootZone.runBinary (dart:async/zone.dart:1665)
#10     _FutureListener.handleError (dart:async/future_impl.dart:162)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:779)
#12     Future._propagateToListeners (dart:async/future_impl.dart:800)
#13     Future._completeError (dart:async/future_impl.dart:575)
#14     Future._chainForeignFuture.<anonymous closure> (dart:async/future_impl.dart:520)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
}

**Comment by clragon** [comment]
The site is having issues and has therefore enabled DDOS protection, blocking the API usage.
This means the app can not reach the server for the duration. Please be patient while the site staff resolves this.
There is nothing we can do on our end.

**Comment by TipsyTheCat** [comment]
> The site is having issues and has therefore enabled DDOS protection, blocking the API usage.
> This means the app can not reach the server for the duration. Please be patient while the site staff resolves this.
> There is nothing we can do on our end.

I think it's worth noting this in the app when it receives a 403 response. something like "e621 may have temporarily disabled the API (required by 3rd-party apps)" or something under the "failed to load posts" message
